#!/usr/bin/env node
// Generates REPOS.md and VERSION.md. Never hand-edit the output.
//
//   node scripts/generate.mjs           rewrite both files
//   node scripts/generate.mjs --check   exit 1 if either is stale (used by CI)
//
// Design note: this records only facts that change RARELY — repository name,
// description, archive status, published package version. It deliberately does
// not record commit SHAs or last-push dates: those change constantly, which
// would make --check fail daily and train everyone to ignore the signal.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OWNER = "wazootech";
const MAP_VERSION = "0.1.0";

/**
 * Tier 1 is the curated showcase in README.md. It is maintained BY HAND on
 * purpose: the generator must never decide what counts as "the platform".
 * Keep in sync with the platform table in README.md.
 */
const TIER1 = [
  "wazoo-api",
  "worlds-api",
  "wazoo-console",
  "wazoo-desktop",
  "wazoo-client-ts",
  "worlds-client-ts",
  "worlds-sdk-ts",
  "worlds-kit",
  "sparql-engine",
  "wazoo-tools",
  "wazoo-cli",
  "wazoo-skills",
  "worlds-libsql",
  "worlds-sqlite",
  "worlds-postgres",
  "worlds-cloudflare",
  "worlds-indexeddb",
  "docs.wazoo.dev",
  "wazoo.dev",
];

/** Published packages, so VERSION.md can record what is actually installable. */
const PACKAGES = {
  "wazoo-api": null,
  "worlds-api": null,
  "wazoo-console": null,
  "wazoo-desktop": null,
  "wazoo-client-ts": "@wazoo/client",
  "worlds-client-ts": "@worlds/client",
  "worlds-sdk-ts": "@worlds/sdk",
  "worlds-kit": "@wazoo/worlds-kit",
  "sparql-engine": "@wazoo/sparql-engine",
  "wazoo-tools": "@wazoo/tools",
  "wazoo-cli": null,
  "wazoo-skills": null,
  "worlds-libsql": "@worlds/libsql",
  "worlds-sqlite": "@worlds/sqlite",
  "worlds-postgres": "@worlds/postgres",
  "worlds-cloudflare": "@worlds/cloudflare",
  "worlds-indexeddb": "@worlds/indexeddb",
  "docs.wazoo.dev": null,
  "wazoo.dev": null,
};

const BANNER = "<!-- generated by scripts/generate.mjs — do not edit by hand -->";
const TIMESTAMP = /^<!-- generated-at: .*-->$/m;

function gh(args) {
  try {
    return execFileSync("gh", args, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      maxBuffer: 64 * 1024 * 1024,
    });
  } catch (error) {
    throw new Error(
      `gh ${args.join(" ")} failed: ${error.stderr?.toString().trim() || error.message}`,
    );
  }
}

function ghJson(args) {
  return JSON.parse(gh(args));
}

async function packageVersion(pkg) {
  if (!pkg) return null;
  try {
    const res = await fetch(`https://jsr.io/${pkg}/meta.json`, {
      headers: { accept: "application/json" },
    });
    if (!res.ok) return null;
    const meta = await res.json();
    return typeof meta.latest === "string" ? meta.latest : null;
  } catch {
    return null;
  }
}

async function listRepos() {
  const all = [];
  for (let page = 1; ; page++) {
    const batch = ghJson([
      "api",
      `orgs/${OWNER}/repos?per_page=100&page=${page}&type=all`,
    ]);
    if (!Array.isArray(batch) || batch.length === 0) break;
    all.push(...batch);
    if (batch.length < 100) break;
  }
  return all;
}

const cell = (value) => String(value ?? "").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();

function renderRepos(repos) {
  const publicRepos = repos.filter((r) => !r.private);
  const internal = repos.length - publicRepos.length;
  const current = publicRepos.filter((r) => !r.archived).sort((a, b) => a.name.localeCompare(b.name));
  const archived = publicRepos.filter((r) => r.archived).sort((a, b) => a.name.localeCompare(b.name));

  const table = (rows) =>
    [
      "| Repository | What it is |",
      "| --- | --- |",
      ...rows.map(
        (r) =>
          `| [${r.name}](https://github.com/${OWNER}/${r.name}) | ${
            cell(r.description) || "_(no description)_"
          } |`,
      ),
    ].join("\n");

  return `${BANNER}
<!-- generated-at: ${new Date().toISOString()} -->

# Repository inventory

Every public repository in the \`${OWNER}\` organization: **${current.length} current**,
**${archived.length} archived**. Generated from the organization, so it is never
out of date by neglect.

Private repositories are intentionally not listed. ${internal} internal
${
    internal === 1 ? "repository is" : "repositories are"
  } omitted by design — this is a public map.

The curated view of the platform — the ones worth reading first — is the table in
[README.md](README.md).

## Current (${current.length})

${table(current)}

## Archived (${archived.length})

Frozen. Linked for history, not for use.

${table(archived)}
`;
}

async function renderVersion(repos) {
  const byName = new Map(repos.map((r) => [r.name, r]));
  const rows = [];

  for (const name of TIER1) {
    const repo = byName.get(name);
    if (!repo) {
      rows.push(`| ${name} | **not found in the organization** | — | — |`);
      continue;
    }
    const pkg = PACKAGES[name] ?? null;
    const version = await packageVersion(pkg);
    const state = repo.archived ? "archived" : repo.isEmpty ? "empty" : "current";
    rows.push(
      `| [${name}](https://github.com/${OWNER}/${name}) | ${state} | ${
        pkg ? `\`${pkg}\`` : "—"
      } | ${version ?? (pkg ? "_unpublished_" : "—")} |`,
    );
  }

  return `${BANNER}
<!-- generated-at: ${new Date().toISOString()} -->

# Versions

**This map does not pin a platform release.** There is no coherent cross-repo
release process for Wazoo yet — the repositories version and publish
independently. This file records what each part looked like when the map was
last regenerated; it is a record, not a lockfile. Do not treat two rows agreeing
as a supported combination.

## Map version

${MAP_VERSION} — the version of this map, not of the platform.

## Platform repositories

| Repository | State | Package | Latest |
| --- | --- | --- | --- |
${rows.join("\n")}

## Why there are no commit hashes

arsumbris pins one tag across every part of its system, so a version there is
meaningful. Wazoo has no equivalent, and writing commit hashes here would imply
a coherence that does not exist. Adding one is tracked as an open question in
[wazootech/workspace#149](https://github.com/wazootech/workspace/issues/149).
`;
}

async function main() {
  const check = process.argv.includes("--check");
  const repos = await listRepos();
  const outputs = [
    ["REPOS.md", renderRepos(repos)],
    ["VERSION.md", await renderVersion(repos)],
  ];

  let stale = 0;
  for (const [name, content] of outputs) {
    const path = join(ROOT, name);
    if (!check) {
      writeFileSync(path, content, "utf8");
      console.log(`wrote ${name}`);
      continue;
    }
    let existing = "";
    try {
      existing = readFileSync(path, "utf8");
    } catch {
      /* missing file counts as stale */
    }
    // The timestamp is the only intentionally volatile line.
    if (existing.replace(TIMESTAMP, "") !== content.replace(TIMESTAMP, "")) {
      console.error(`stale: ${name} — run: node scripts/generate.mjs`);
      stale++;
    }
  }

  if (check) {
    if (stale > 0) {
      console.error(`\n${stale} generated file(s) out of date.`);
      process.exit(1);
    }
    console.log("generated files are up to date");
  }
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
